name: cder2
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alabaster=0.7.12
  - alsa-lib=1.2.7.2
  - appdirs=1.4.4
  - asttokens=2.0.5
  - attr=2.5.1
  - babel=2.11.0
  - backcall=0.2.0
  - biopython=1.78
  - blas=1.0
  - bokeh=3.1.0
  - boost-cpp=1.78.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - cffi=1.15.1
  - cgal-cpp=5.5.2
  - charset-normalizer=2.0.4
  - colorama=0.4.6
  - comm=0.1.2
  - contourpy=1.0.5
  - cryptography=39.0.1
  - cycler=0.11.0
  - cython=0.29.33
  - dbus=1.13.18
  - debugpy=1.5.1
  - decorator=5.1.1
  - docutils=0.18.1
  - eigen=3.3.7
  - executing=0.8.3
  - expat=2.4.9
  - fftw=3.3.10
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - fonttools=4.25.0
  - freetype=2.12.1
  - gettext=0.21.1
  - giflib=5.2.1
  - glib=2.74.1
  - glib-tools=2.74.1
  - gmp=6.2.1
  - gst-plugins-base=1.20.3
  - gstreamer=1.20.3
  - gudhi=3.7.1
  - icu=70.1
  - idna=3.4
  - imagesize=1.4.1
  - intel-openmp=2021.4.0
  - ipykernel=6.19.2
  - ipython=8.12.0
  - jack=1.9.21
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.1.1
  - jpeg=9e
  - jupyter_client=8.1.0
  - jupyter_core=5.3.0
  - kiwisolver=1.4.4
  - krb5=1.19.4
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcap=2.66
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcups=2.3.3
  - libdb=6.2.32
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libevent=2.1.10
  - libffi=3.4.2
  - libflac=1.4.2
  - libgcc-ng=12.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.74.1
  - libiconv=1.17
  - libllvm14=14.0.6
  - libogg=1.3.5
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=14.5
  - libsndfile=1.1.0
  - libsodium=1.0.18
  - libsqlite=3.40.0
  - libstdcxx-ng=12.2.0
  - libtiff=4.5.0
  - libtool=2.4.6
  - libudev1=253
  - libuuid=1.41.5
  - libvorbis=1.3.7
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.14
  - libzlib=1.2.13
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mpfr=4.2.0
  - mpg123=1.31.3
  - munkres=1.1.4
  - mysql-common=8.0.32
  - mysql-libs=8.0.32
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - nspr=4.33
  - nss=3.78
  - numexpr=2.8.4
  - numpy=1.23.5
  - numpy-base=1.23.5
  - openssl=1.1.1t
  - packaging=23.0
  - pandas=1.5.3
  - parso=0.8.3
  - pcre2=10.40
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.0.1
  - platformdirs=2.5.2
  - ply=3.11
  - pooch=1.4.0
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pulseaudio=14.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.11.2
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pysocks=1.7.1
  - python=3.11.3
  - python-dateutil=2.8.2
  - python_abi=3.11
  - pytz=2022.7
  - pyyaml=6.0
  - pyzmq=23.2.0
  - qt-main=5.15.6
  - readline=8.2
  - requests=2.28.1
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - seaborn=0.12.2
  - setuptools=66.0.0
  - sip=6.7.7
  - six=1.16.0
  - snowballstemmer=2.2.0
  - sphinx=5.0.2
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - sqlite=3.41.2
  - stack_data=0.2.0
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - toml=0.10.2
  - tornado=6.2
  - traitlets=5.7.1
  - tzdata=2023c
  - urllib3=1.26.15
  - wcwidth=0.2.5
  - wheel=0.38.4
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xyzservices=2022.9.0
  - xz=5.2.10
  - yaml=0.2.5
  - zeromq=4.3.4
  - zlib=1.2.13
  - zstd=1.5.5
  # Download gda-public and follow their instructions to install
  # the package from https://github.com/geomdata/gda-public/
  # Note: This environment file includes all dependencies for gda-public
  # so you don't need to install them from their requirements.txt